name: gh-pages

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Mudar para a pasta desejada
      run: cd IMC
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Publish with dotnet
      run: dotnet publish IMC/IMC.csproj --configuration Release --output dist
    # changes the base-tag in index.html from '/' to 'IMC' to match GitHub Pages repository subdirectory
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/wwwroot
